<?php
// Local mirror of the book_zip table: which zip archive holds a given book id.
//
// The table is tiny (one row per archive, a few hundred rows) but it was queried
// on every download and every cover-cache miss with a `id BETWEEN start_id AND
// end_id` predicate that Postgres cannot serve from one index. Keeping the same
// data in a generated PHP file lets opcache hold it in memory, so those paths
// need no database at all.
//
// The file is rewritten by tools/update_zip_list.php (after every import/reindex,
// under the dbupdate lock) and regenerated by the addbook module when it adds an
// archive. Postgres stays the source of truth: if the file is missing or stale we
// fall back to SQL and rebuild it.
//
// Guarded defines: this file is included both from the web app (init.php) and
// standalone from CLI tools.
if (!defined('CACHE_PATH')) {
	define('CACHE_PATH', '/cache/');
}
define('BOOK_ZIP_FILE', CACHE_PATH . 'book_zip.php');

// $fb2Rows/$usrRows: lists of [startId, endId, filename], filename being the full
// path as stored in the table (/flibusta/... or /cache/local/...).
function book_zip_file_write(array $fb2Rows, array $usrRows): bool {
	$sort = function (array $a, array $b) { return $a[0] <=> $b[0]; };
	usort($fb2Rows, $sort);
	usort($usrRows, $sort);
	$payload = "<?php\n// Generated by tools/update_zip_list.php - do not edit.\n"
		. "return " . var_export(['fb2' => array_values($fb2Rows), 'usr' => array_values($usrRows)], true) . ";\n";
	$tmp = BOOK_ZIP_FILE . '.' . getmypid() . '.tmp';
	if (@file_put_contents($tmp, $payload) === false) {
		error_log('book_zip_store: cannot write ' . $tmp);
		return false;
	}
	if (!@rename($tmp, BOOK_ZIP_FILE)) { // atomic swap, readers never see a partial file
		@unlink($tmp);
		error_log('book_zip_store: cannot replace ' . BOOK_ZIP_FILE);
		return false;
	}
	if (function_exists('opcache_invalidate')) {
		@opcache_invalidate(BOOK_ZIP_FILE, true);
	}
	return true;
}

// Rebuilds the file from the table. Used by the addbook module (which INSERTs a
// single archive row) and as self-healing when the file is missing.
function book_zip_file_regenerate_from_db($dbh): bool {
	try {
		$stmt = $dbh->prepare("SELECT filename, start_id, end_id, usr FROM book_zip");
		$stmt->execute();
		$fb2 = [];
		$usr = [];
		while ($row = $stmt->fetch(PDO::FETCH_OBJ)) {
			$entry = [(int)$row->start_id, (int)$row->end_id, (string)$row->filename];
			if ((int)$row->usr === 1) {
				$usr[] = $entry;
			} else {
				$fb2[] = $entry;
			}
		}
	} catch (Throwable $e) {
		error_log('book_zip_store: regeneration from DB failed: ' . $e->getMessage());
		return false;
	}
	return book_zip_file_write($fb2, $usr);
}

function book_zip_map_load(): ?array {
	static $map = null;
	static $loaded = false;
	if (!$loaded) {
		$loaded = true;
		if (is_readable(BOOK_ZIP_FILE)) {
			$data = @include BOOK_ZIP_FILE;
			if (is_array($data) && isset($data['fb2'], $data['usr'])) {
				$map = $data;
			}
		}
	}
	return $map;
}

// Returns the archive path holding $bookid, or null when no archive covers it.
// $usr selects the non-fb2 archives (usr=1 in the table), matching the SQL this
// replaces. Falls back to the database when the generated file is unavailable.
function book_zip_lookup(int $bookid, bool $usr, $dbh = null): ?string {
	$map = book_zip_map_load();
	if ($map !== null) {
		foreach ($map[$usr ? 'usr' : 'fb2'] as $row) {
			if ($bookid >= $row[0] && $bookid <= $row[1]) {
				return $row[2];
			}
		}
		return null;
	}
	// No usable file - answer from the table and rebuild it for next time.
	if ($dbh === null) {
		$dbh = $GLOBALS['dbh'] ?? null;
	}
	if ($dbh === null) {
		return null;
	}
	$stmt = $dbh->prepare("SELECT filename FROM book_zip WHERE :id BETWEEN start_id AND end_id AND usr=:u");
	$stmt->execute([':id' => $bookid, ':u' => $usr ? 1 : 0]);
	$row = $stmt->fetch(PDO::FETCH_OBJ);
	book_zip_file_regenerate_from_db($dbh);
	return $row ? (string)$row->filename : null;
}
