<?php
/**
 * The book-id to archive mapping, as a generated PHP file.
 *
 * Every book request has to answer the same question - which zip under /flibusta
 * (or /cache/local) holds this id - and used to answer it with
 * `SELECT ... FROM book_zip WHERE ? BETWEEN start_id AND end_id`, once per
 * download, once more for the in-browser reader, once more for the cover. The data
 * behind it is tiny (one row per archive, a few thousand at most), changes only
 * when the archives are rescanned or a book is added locally, and is a pure
 * function of the file names on disk.
 *
 * So it is written out as a PHP array instead. OPcache keeps the parsed array in
 * shared memory, which makes a lookup an in-process binary search rather than a
 * round trip, and - unlike a Redis copy - it works the same in a deployment that
 * has no Redis at all.
 *
 * The file is regenerated by tools/update_zip_list.php (archive rescan, which also
 * refills the book_zip table) and by the addbook module. It is written to a temp
 * name and renamed into place, so a reader never sees half a file. book_zip stays
 * as the fallback for a deployment that has not rescanned yet.
 *
 * NB: OPcache must keep validating timestamps (the default) or workers will serve
 * the previous library layout until php-fpm is reloaded - see the note in
 * phpdocker/php-fpm/Dockerfile.
 *
 * Deliberately free of ROOT_PATH/init.php so the CLI tools can include it alone.
 */

if (!defined('ZIP_INDEX_FILE')) {
	define('ZIP_INDEX_FILE', (defined('CACHE_PATH') ? CACHE_PATH : '/cache/') . 'zip_index.php');
}

/**
 * Writes the index.
 *
 * @param list<array{0:int,1:int,2:string}> $fb2 [start_id, end_id, archive path], usr=0
 * @param list<array{0:int,1:int,2:string}> $usr the same for usr=1
 * @return bool false when the file could not be written (the caller keeps working
 *              off book_zip in that case)
 */
function zip_index_write(array $fb2, array $usr): bool
{
	$sort = static function (array $a, array $b): int {
		return $a[0] <=> $b[0];
	};
	usort($fb2, $sort);
	usort($usr, $sort);

	$payload = "<?php\n"
		. "// Generated by tools/update_zip_list.php / the addbook module. Do not edit.\n"
		. '// ' . date('Y-m-d H:i:s') . ', ' . (count($fb2) + count($usr)) . " archives.\n"
		. 'return ' . var_export(['fb2' => array_values($fb2), 'usr' => array_values($usr)], true) . ";\n";

	$tmp = ZIP_INDEX_FILE . '.' . getmypid() . '.tmp';
	if (@file_put_contents($tmp, $payload, LOCK_EX) === false) {
		error_log('Flibusta: cannot write the zip index at ' . $tmp);
		return false;
	}
	// Atomic within the same filesystem, so a concurrent request either sees the
	// old index or the new one.
	if (!@rename($tmp, ZIP_INDEX_FILE)) {
		error_log('Flibusta: cannot install the zip index at ' . ZIP_INDEX_FILE);
		@unlink($tmp);
		return false;
	}
	if (function_exists('opcache_invalidate')) {
		// rename() leaves OPcache holding the old inode's compiled form until its
		// next timestamp check; drop it now so the very next request is correct.
		@opcache_invalidate(ZIP_INDEX_FILE, true);
	}
	return true;
}

/** Rebuilds the index from the book_zip table. Used after the addbook module writes a row. */
function zip_index_write_from_db(PDO $dbh): bool
{
	$rows = $dbh->query("SELECT filename, start_id, end_id, usr FROM book_zip ORDER BY usr, start_id")
		->fetchAll(PDO::FETCH_OBJ);
	$fb2 = [];
	$usr = [];
	foreach ($rows as $row) {
		$entry = [(int)$row->start_id, (int)$row->end_id, (string)$row->filename];
		if ((int)$row->usr === 0) {
			$fb2[] = $entry;
		} else {
			$usr[] = $entry;
		}
	}
	return zip_index_write($fb2, $usr);
}

/** The parsed index, or null when there is no index file yet. */
function zip_index_load(): ?array
{
	static $index = false;   // false = not looked at yet, null = absent
	if ($index !== false) {
		return $index;
	}
	if (!is_file(ZIP_INDEX_FILE)) {
		$index = null;
		return null;
	}
	$loaded = @include ZIP_INDEX_FILE;
	if (!is_array($loaded) || !isset($loaded['fb2']) || !isset($loaded['usr'])) {
		error_log('Flibusta: the zip index is unreadable, falling back to the book_zip table.');
		$index = null;
		return null;
	}
	$index = $loaded;
	return $index;
}

/**
 * The archive holding a book, '' when none covers it, or null when there is no
 * index file and the caller should query book_zip instead.
 *
 * Where ranges overlap, the one starting latest wins. The SQL this replaces picked
 * an arbitrary row among the matches; preferring the narrowest range is both
 * deterministic and what the addbook module needs, since a locally added book is
 * registered as a one-book range (start == end) that sits inside whatever dump
 * archive happens to span it.
 */
function zip_index_lookup(int $id, int $usr): ?string
{
	$index = zip_index_load();
	if ($index === null) {
		return null;
	}
	$ranges = $index[$usr === 0 ? 'fb2' : 'usr'] ?? [];
	$count  = count($ranges);
	if ($count === 0) {
		return '';
	}

	// Upper bound: the first range that starts after $id.
	$lo = 0;
	$hi = $count;
	while ($lo < $hi) {
		$mid = ($lo + $hi) >> 1;
		if ($ranges[$mid][0] <= $id) {
			$lo = $mid + 1;
		} else {
			$hi = $mid;
		}
	}
	for ($i = $lo - 1; $i >= 0; $i--) {
		if ($ranges[$i][1] >= $id) {
			return (string)$ranges[$i][2];
		}
	}
	return '';
}
