server {
    listen 80 default;

    client_max_body_size 508M;

    access_log /var/log/nginx/application.access.log;


    root /application/public;
    index index.php;

    # try to serve file directly, fallback to index.php
    location / {
        try_files $uri /index.php$is_args$args;
    }

    if (!-e $request_filename) {
        rewrite ^.*$ /index.php last;
    }

    location ~ \.php$ {
        add_header 'Content-Security-Policy' 'worker-src * blob:';
	
        include fastcgi_params;
        proxy_set_header Authorization $http_authorization;
        proxy_pass_header Authorization;

        fastcgi_pass php-fpm:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_buffers 16 16k;
        fastcgi_buffer_size 32k;
        
        fastcgi_param REMOTE_ADDR            $remote_addr;
        fastcgi_param REQUEST_URI            $request_uri;
        fastcgi_param HTTP_HOST              $http_host;
        fastcgi_param HTTP_X_REAL_IP         $remote_addr;
        fastcgi_param HTTP_X_FORWARDED_FOR   $proxy_add_x_forwarded_for;
        fastcgi_param HTTP_X_FORWARDED_PROTO $scheme;
        fastcgi_param HTTP_USER_AGENT        $http_user_agent;  
        fastcgi_param PHP_AUTH_USER          $remote_user;
        fastcgi_param HTTP_AUTHORIZATION     $http_authorization;
    }
    
}
