location ^~ /flibusta {
    
    root /srv;
    index index.php;

    access_log /config/log/nginx/flibusta.access.log;
    error_log /config/log/nginx/flibusta.error.log info;
    
    try_files $uri $uri/ /flibusta/index.php$is_args$args;

    location ~ \.php$ {
        add_header 'Content-Security-Policy' 'worker-src * blob:';
        proxy_set_header Authorization $http_authorization;
        proxy_pass_header Authorization;
        include fastcgi_params;

        fastcgi_split_path_info ^/flibusta/(.+?\.php)(.*)$;
        set $path_info $fastcgi_path_info;

        fastcgi_param SCRIPT_FILENAME /application/public/$fastcgi_script_name;
        fastcgi_param PATH_INFO $path_info;
        fastcgi_param PATH_TRANSLATED /application/public$path_info;

        fastcgi_intercept_errors on;
        fastcgi_buffers 16 16k;
        fastcgi_buffer_size 32k;
         
        fastcgi_param REMOTE_ADDR            $remote_addr;
        fastcgi_param HTTP_X_REAL_IP         $remote_addr;
        fastcgi_param HTTP_X_FORWARDED_FOR   $proxy_add_x_forwarded_for;
        fastcgi_param HTTP_X_FORWARDED_PROTO $scheme;
        fastcgi_param HTTP_HOST              $http_host;
        fastcgi_param REQUEST_URI            $request_uri;
        fastcgi_param HTTP_USER_AGENT        $http_user_agent;  
        fastcgi_param PHP_AUTH_USER          $remote_user;
        fastcgi_param HTTP_AUTHORIZATION     $http_authorization;

        fastcgi_pass {ADDRESS_OR_NAME_OF_FLIBUSTA_CONTAINER}:9000;
        fastcgi_index index.php;

    }
    
}
