version: '3.1'
services:
    postgres:
        build: phpdocker/pg
        working_dir: /application
        volumes:
            - 'db-data:/var/lib/postgresql/data'
            - './application:/application'
        environment:
            - POSTGRES_USER=flibusta
            - POSTGRES_PASSWORD=flibusta
            - POSTGRES_DB=flibusta
        ports:
            - '27101:5432'

    webserver:
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
            - './application:/application'
            - './cache:/application/cache'
            - './Flibusta.Net:/application/flibusta'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '27100:80'

    php-fpm:
        build: phpdocker/php-fpm
        working_dir: /application
        volumes:
            - './application:/application'
            - './cache:/application/cache'
            - './Flibusta.Net:/application/flibusta'
            - './FlibustaSQL:/application/sql'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/local-custom.ini'
            - './phpdocker/php-fpm/php-fpm.conf:/usr/local/etc/php-fpm.d/zz-php-fpm.conf'
        environment:
            - FLIBUSTA_DBUSER=flibusta
            - FLIBUSTA_DBNAME=flibusta
            - FLIBUSTA_DBTYPE=postgres
            - FLIBUSTA_DBHOST=postgres
            - FLIBUSTA_DBPASSWORD_FILE=/run/secrets/FLIBUSTA_PWD
        secrets:
            - FLIBUSTA_PWD


volumes:
    db-data:
secrets:
    FLIBUSTA_PWD:
        file: ./secrets/flibusta_pwd.txt