<?php
global $url;
global $command_running;
global $service_name;

// returns literal or false 
function service_opname() {
	if (isset($_GET['empty'])) 
		return "empty";
	if (isset($_GET['getcovers']))
		return "getcovers"; 
	if (isset($_GET['import']))
		return  "import";
	if (isset($_GET['reindex']))
		return "reindex";
	if (isset($_GET['download']))
		return "download";
	if (isset($_GET['getdaily']))
		return "getdaily";
	return false;
}

$url->title = 'Сервис и настройки';
exec("flock -n ".ADMINOPLOCKFILE." -c 'echo 1'",$notused,$command_running);

$service_name = service_opname();

if ($command_running) {
	if (isset($_GET['opname'])) {
    	header("Refresh: 10; url=".$webroot."/service?opname=".$_GET['opname']);
	}else  {
		header("Refresh: 10; url=".$webroot."/service");
	} 
} elseif ($service_name !== false){
    header("Refresh: 2; url=".$webroot."/service?opname=".$service_name);
}


