version: '3.1'
services:
    postgres:
        build: phpdocker/pg
        working_dir: /application
        volumes:
            - 'db-data:/var/lib/postgresql/data'
            - './application:/application'
        environment:
            - POSTGRES_USER=flibusta
            - POSTGRES_PASSWORD=flibusta
            - POSTGRES_DB=flibusta
        ports:
            - '27101:5432'

    webserver:
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
            - flibusta_public_files:/application/public
            - './cache:/application/cache'
            - './Flibusta.Net:/application/flibusta'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '27100:80'

    php-fpm:
        build: phpdocker/php-fpm
        working_dir: /application
        volumes:
            - './Flibusta.Net:/flibusta:ro'
            - './FlibustaSQL:/sql'
            - './cache/:/cache'
            - flibusta_public_files:/public_mountpoint

        environment:
            - FLIBUSTA_DBUSER=flibusta
            - FLIBUSTA_DBNAME=flibusta
            - FLIBUSTA_DBTYPE=postgres
            - FLIBUSTA_DBPASSWORD_FILE=/run/secrets/FLIBUSTA_PWD
            - MAX_FB2_SIZE_2_DISPLAY=100000000
            - FLIBUSTA_APP_ADMIN=flibustadmin
            - FLIBUSTA_APP_ADMIN_PASSWORD_FILE=/run/secrets/FLIBUSTA_APP_ADMIN_PWD
            - FLIBUSTA_TURSTED_NET='192.168.1.0/24'
            - FLIBUSTA_ALLOW_ADMIN_ACCESS_BY_HTTP='true'
        secrets:
            - FLIBUSTA_PWD
            - FLIBUSTA_APP_ADMIN_PWD



volumes:
    db-data:
secrets:
    FLIBUSTA_PWD:
        file: ./secrets/flibusta_pwd.txt
    FLIBUSTA_APP_ADMIN_PWD:
        file: ./secrets/flibusta_app_admin_pwd.txt